# Stage 1
FROM node:15.12.0-alpine3.10 as build-step
RUN mkdir -p /apps/api
WORKDIR /apps/api
COPY ./apps/api/package.json /apps/api
COPY ./apps/api/tsconfig.build.json /apps/api
COPY ./apps/api/tsconfig.json /apps/api
COPY ./apps/api/nest-cli.json /apps/api
RUN npm install
COPY ./apps/api/src/ /apps/api/src/
RUN npm run build
EXPOSE 80
