# Stage 1

FROM node:15.12.0-alpine3.10 as build-step

RUN mkdir -p /apps/web

WORKDIR /apps/web

COPY /apps/web/package.json /apps/web

RUN npm install

COPY /apps/web /apps/web

RUN npm run build --prod
 
# Stage 2

FROM nginx:1.19.8-alpine
RUN rm -rf /usr/share/nginx/html/*
COPY nginx.web.conf /etc/nginx/nginx.conf
COPY --from=build-step /apps/web/dist/web /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]