INSERT INTO [dbo].[RoadSegments]
           ([RouteName]
           ,[SegmentStatus]
           ,[RoadSegmentLength]
           ,[District]
           ,[County]
           ,[Location]
           ,[MaintenanceOffice]
           ,[MaintenanceOfficeNumber]
           ,[FromToDescription]
           ,[GroupName])
     VALUES
           ('TEST'
           ,'TEST'
           ,2
           ,'TEST'
           ,'TEST'
           ,'TEST'
           ,'TEST'
           ,'TEST'
           ,'TEST'
           ,'TEST')